name: chaoxing

on:
  push:

env:
    USERNAME: ${{secrets.USERNAME}}
    PASSWORD: ${{secrets.PASSWORD}}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt update
        apt install php-fpm php-mysql php-curl php-gd php-mbstring php-mcrypt php-xml php-xmlrpc php-zip php-opcache php-cli -y

    - name: Starting checkin
      run: php main.php -A ${{secrets.USERNAME}} -P ${{secrets.PASSWORD}}
