name: ChaoxingSign

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 7-18 * * *'

env:
  TZ: Asia/Shanghai
  USERNAME: ${{secrets.USERNAME}}
  PASSWORD: ${{secrets.PASSWORD}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install php-fpm php-mysql php-curl php-gd php-mbstring php-xml php-xmlrpc php-zip php-cli -y

    - name: Starting checkin
      run: php main.php -A ${{secrets.USERNAME}} -P ${{secrets.PASSWORD}}
