name: ChaoxingSign

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 7-18 * * *'

env:
  TZ: Asia/Shanghai
  USERNAME: ${{secrets.USERNAME}}
  PASSWORD: ${{secrets.PASSWORD}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 7.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: curl, mbstring

    - name: Starting checkin
      run: php main.php -A ${{secrets.USERNAME}} -P ${{secrets.PASSWORD}}
